// Generated by Wrangler on Thu Aug 29 2024 15:42:41 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	TWITCH_CLIENT_ID: string;
	TWITCH_CLIENT_SECRET: string;
	TWITCH_APP_ACCESS_TOKEN: string;
	GATHERER_QUEUE: Queue;
	INDEXER_QUEUE: Queue;
	VECTORIZE: VectorizeIndex;
	AI: Ai;
}
